
kept_collections = [
'keep *_particleFlow_*_*',
'keep *_offlineBeamSpot_*_*',
'keep *_pfPhotonTranslator_*_*',
'keep *_*_PhotonCutBasedID*_*',
'keep ClusterSummary_clusterSummaryProducer__RECO',
'keep *_ak5PFJets_*_*',
'keep *_ak7PFJets_*_*',
'keep *_fixedGridRho*__*',
'keep *_kt4PFJets_*_*',
'keep *_kt6PFJets_*_*',
'keep *_pfJetsTR_*_*',
'keep *_conditionsInEdm_*_*',
'keep *_logErrorHarvester_*_*',
'keep *_TriggerResults_*_*',
'keep GenEventInfoProduct_generator__*',
'keep patElectrons_*atElectronsTR__*',
'keep patJetCorrFactorsedmValueMap_patJetCorrFactorsTR__*',
'keep *_patJetsTR__*',
'keep *_*selectedPatJets*_*_*',
'keep recoGenJetsedmAssociation_patJetGenJetMatchTR__*',
'keep patJets_smearedPatJets__*',
'keep patMETs_patMETsTR__*',
'keep patMETs_patPFMetTR__*',
'keep patMETs_patType1CorrectedPFMetTR__*',
'keep patMuons_patMuonsTR__*',
'keep patMuons_selectedPatMuonsTR__*',
'keep patMuons_tightmuons__*',
'keep *_*hoton*_*_*',

'keep PileupSummaryInfos_addPileupInfo__*',
'keep recoConversions_*onversions*__*',
'keep recoGenMETs_genMetTrue__*',
'keep recoGenParticles_genParticles__*',
'keep recoGenParticlesedmAssociation_*Match*__*',
'keep recoGsfElectrons_gsfElectrons__RECO',
'keep recoMETs_htMetAK5__RECO',
'keep recoMETs_htMetAK7__RECO',
'keep recoMETs_htMetIC5__RECO',
'keep recoMETs_htMetKT4__RECO',
'keep recoMETs_htMetKT6__RECO',
'keep recoMETs_tcMet__RECO',
'keep recoMETs_tcMetWithPFclusters__RECO',
'keep recoMuons_muons__RECO',
'keep recoPFCandidates_pfElectronsTR__*',
'keep recoPFCandidates_pfMuonsTR__*',
'keep recoPFCandidates_pfSelectedElectronsTR__*',
'keep recoPFCandidates_pfSelectedMuonsTR__*',
'keep recoVertexs_goodOfflinePrimaryVertices__*',
'keep recoVertexs_offlinePrimaryVertices__RECO',
'keep triggerTriggerEvent_hltTriggerSummaryAOD__*',
'keep edmMergeableCounter_*_*_*',
]

